version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: expfactory/survey-generator
          registry: quay.io
          deploy: false
          tag: latest
          filters:
            branches:
              ignore: 
                - master
                - docs*
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(echo "${CIRCLE_SHA1}" | cut -c1-10)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   MANUAL_VERSION=$(cat VERSION)
                   docker tag quay.io/expfactory/survey-generator:latest quay.io/expfactory/survey-generator:${MANUAL_VERSION}
                   docker images
            - run:
                name: Run Tests
                command: |
                   EXPFACTORY_SURVEY=state-mindfulness-survey
                   CONTAINER_NAME=quay.io/expfactory/survey-generator
                   DOCKER_TAG=latest
                   echo "The Experiment Factory!"
                   echo "[run] docker run ${CONTAINER_NAME}:${DOCKER_TAG} start"
                   docker run --name surveys -td --entrypoint bash ${CONTAINER_NAME}:${DOCKER_TAG}
                   echo "[cp] docker cp ./tmp/src/. surveys:/code/"
                   docker cp $PWD/${EXPFACTORY_SURVEY}/. surveys:/data/
                   echo "[exec] docker exec surveys ls /code"
                   docker exec surveys ls /code
                   echo "[exec] docker exec surveys ls /data"
                   docker exec surveys ls /data
                   echo "[exec] docker exec surveys /bin/bash /code/entrypoint.sh start"
                   docker exec surveys /bin/bash /code/entrypoint.sh start
                   echo "Step 2: Saving result as artifact for inspection"
                   mkdir -p /tmp/survey /tmp/archive
                   echo "[cp] docker cp surveys:/data/. /tmp/survey/"
                   docker cp surveys:/data/. /tmp/survey/
                   tar -zcvf "/tmp/archive/${EXPFACTORY_SURVEY}.tar.gz" /tmp/survey
                   mv /tmp/archive/${EXPFACTORY_SURVEY}.tar.gz /tmp/survey
                   docker stop surveys
            - store_artifacts:
                path: /tmp/survey

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: expfactory/survey-generator
          registry: quay.io
          tag: latest
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with Expfactory Survey Generator
                command: |
                   DOCKER_TAG=$(echo "${CIRCLE_SHA1}" | cut -c1-10)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   docker tag quay.io/expfactory/survey-generator:latest quay.io/expfactory/survey-generator:${DOCKER_TAG}
                   MANUAL_VERSION=$(cat VERSION)
                   docker tag quay.io/expfactory/survey-generator:latest quay.io/expfactory/survey-generator:${MANUAL_VERSION}
                   docker push quay.io/expfactory/survey-generator
